{
  config,
  lib,
  pkgs,
  ...
}: let
  inherit (lib) mkEnableOption mkIf mkOption types;
  cfg = config.myOptions.git-hooks;
  formattersCfg = config.myOptions.formatters;

  verboseEcho = msg:
    if formattersCfg.verbose
    then ''echo ${lib.escapeShellArg msg}''
    else ":";

  # Generate the per-pattern dispatch block. For each regex pattern we emit a
  # bash `if` that, on match, walks its formatter list in order and runs the
  # first one whose command resolves on PATH or in node_modules/.bin.
  formatterDispatch = let
    perPattern = pattern: invocations: let
      perInvocation = invocation: let
        cmd = builtins.head invocation;
        args = builtins.tail invocation;
      in ''
        if resolved=$(resolve_formatter ${lib.escapeShellArg cmd}); then
          if "$resolved" ${lib.escapeShellArgs args} "$file"; then
            ${verboseEcho "  formatted with ${cmd}"}
            git add -- "$file"
            return 0
          else
            echo "warning: $resolved failed on $file" >&2
          fi
        fi
      '';
    in ''
      if [[ "$file" =~ ${pattern} ]]; then
        ${lib.concatMapStringsSep "\n" perInvocation invocations}
        ${verboseEcho "no formatter resolved for $file"}
        return 0
      fi
    '';
  in
    lib.concatStringsSep "\n"
    (lib.mapAttrsToList perPattern formattersCfg.systemFormatters);

  preCommitScript = ''
    #!/usr/bin/env bash
    # Generated by nixos-config: modules/home/core/git-hooks
    # Pre-commit hook: format staged files in-place, then re-stage them.
    set -euo pipefail

    # If the repo defines its own hook / formatter pipeline, defer entirely.
    # Covers husky, lefthook, the pre-commit framework, and treefmt.
    if [[ -d ".husky" ]] || [[ -d ".husky/_" ]] || [[ -d ".lefthook" ]] \
       || [[ -f "lefthook.yml" ]] || [[ -f "lefthook.yaml" ]] \
       || [[ -f ".lefthook.yml" ]] || [[ -f ".lefthook.yaml" ]] \
       || [[ -f ".pre-commit-config.yaml" ]] || [[ -f ".pre-commit-config.yml" ]] \
       || [[ -f "treefmt.toml" ]] || [[ -f "treefmt.nix" ]]; then
      ${verboseEcho "project-local hook/formatter system detected, skipping global formatter"}
      exit 0
    fi

    # Resolve a formatter command, preferring repo-local installs
    # (node_modules/.bin/<cmd>) before falling back to PATH.
    resolve_formatter() {
      local name="$1"
      if [[ -x "node_modules/.bin/$name" ]]; then
        printf '%s\n' "node_modules/.bin/$name"
        return 0
      fi
      if command -v "$name" >/dev/null 2>&1; then
        printf '%s\n' "$name"
        return 0
      fi
      return 1
    }

    format_file() {
      local file="$1"

      # Skip files that disappeared between staging and hook execution
      # (e.g. removed by another formatter or by the user).
      [[ -f "$file" ]] || return 0

      ${formatterDispatch}

      # No pattern matched: nothing to do.
      return 0
    }

    # Walk staged additions / copies / modifications / renames using NUL
    # delimiters so filenames with whitespace or newlines are handled safely.
    while IFS= read -r -d ''' file; do
      [[ -n "$file" ]] || continue
      format_file "$file"
    done < <(git diff --cached -z --name-only --diff-filter=ACMR)
  '';

  # Build the template tree out-of-store, then symlink via xdg.configFile.
  hookTemplate = pkgs.runCommand "git-hook-templates" {} ''
    mkdir -p $out/hooks
    cat > $out/hooks/pre-commit <<'__EOF__'
    ${preCommitScript}
    __EOF__
    chmod +x $out/hooks/pre-commit
  '';
in {
  options.myOptions.git-hooks = {
    enable = mkEnableOption "Global git hooks";

    preCommit = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "Enable pre-commit hook for formatting";
      };
    };
  };

  config = mkIf cfg.enable {
    # Ensure formatters module is enabled.
    myOptions.formatters.enable = lib.mkDefault true;

    # Place the templates under ~/.config/git/templates/. `git init` (and
    # implicit init via `git clone`) copies everything from
    # `init.templateDir` into the new repo's `.git/`.
    xdg.configFile."git/templates".source = hookTemplate;

    # Tell git to use the template dir for new repos.
    programs.git.settings.init.templateDir = "${config.xdg.configHome}/git/templates";

    # Default formatter config: a global ~/.editorconfig honored by prettier,
    # shfmt, taplo, and most editors. Repo-local .editorconfig with
    # `root = true` overrides this entirely; otherwise the closer file wins
    # per-key.
    home.file.".editorconfig".source = ./files/editorconfig;

    # Formatter packages. Optional ones are included so the hook can use them
    # whenever a matching file is staged.
    home.packages = with pkgs; [
      alejandra
      go
      black
      rustfmt
      shfmt
      yamlfmt
      taplo
      stylua
      prettier
    ];
  };
}
