{pkgs, ...}: [
  "$mod, Q, exec, ${pkgs.ghostty}/bin/ghostty"
  "$mod, D, exec, ${pkgs.fuzzel}/bin/fuzzel"
  "$mod, C, killactive"
  "$mod, M, exit"
  "$mod, F, fullscreen, 0"

  "$mod, h, resizeactive, -20 0"
  "$mod, l, resizeactive, 20 0"
  "$mod, k, movefocus, u"
  "$mod, j, movefocus, d"

  "$mod, left, movewindow, l"
  "$mod, right, movewindow, r"
  "$mod, up, movewindow, u"
  "$mod, down, movewindow, d"
  "$mod SHIFT, h, movewindow, l"
  "$mod SHIFT, l, movewindow, r"
  "$mod SHIFT, k, movewindow, u"
  "$mod SHIFT, j, movewindow, d"

  "$mod ALT, h, movecurrentworkspacetomonitor, l"
  "$mod ALT, l, movecurrentworkspacetomonitor, r"
  "$mod ALT, k, movecurrentworkspacetomonitor, u"
  "$mod ALT, j, movecurrentworkspacetomonitor, d"

  "$mod ALT, 1, focusmonitor, 0"
  "$mod ALT, 2, focusmonitor, 1"
  "$mod ALT, 3, focusmonitor, 2"

  "$mod ALT SHIFT, 1, movewindow, mon:0"
  "$mod ALT SHIFT, 2, movewindow, mon:1"
  "$mod ALT SHIFT, 3, movewindow, mon:2"

  "$mod ALT CTRL, 1, moveworkspacetomonitor, 1 0"
  "$mod ALT CTRL, 2, moveworkspacetomonitor, 2 1"
  "$mod ALT CTRL, 3, moveworkspacetomonitor, 3 2"

  "$mod, 1, workspace, 1"
  "$mod, 2, workspace, 2"
  "$mod, 3, workspace, 3"
  "$mod, 4, workspace, 4"
  "$mod, 5, workspace, 5"
  "$mod, 6, workspace, 6"
  "$mod, 7, workspace, 7"
  "$mod, 8, workspace, 8"
  "$mod, 9, workspace, 9"
  "$mod, 0, workspace, 10"

  "$mod SHIFT, 1, movetoworkspacesilent, 1"
  "$mod SHIFT, 2, movetoworkspacesilent, 2"
  "$mod SHIFT, 3, movetoworkspacesilent, 3"
  "$mod SHIFT, 4, movetoworkspacesilent, 4"
  "$mod SHIFT, 5, movetoworkspacesilent, 5"
  "$mod SHIFT, 6, movetoworkspacesilent, 6"
  "$mod SHIFT, 7, movetoworkspacesilent, 7"
  "$mod SHIFT, 8, movetoworkspacesilent, 8"
  "$mod SHIFT, 9, movetoworkspacesilent, 9"
  "$mod SHIFT, 0, movetoworkspacesilent, 10"

  ", XF86AudioRaiseVolume, exec, pamixer -i 5"
  ", XF86AudioLowerVolume, exec, pamixer -d 5"
  ", XF86AudioMute, exec, pamixer -t"

  "$mod, equal, exec, pamixer -i 5"
  "$mod, minus, exec, pamixer -d 5"
  "$mod, m, exec, pamixer -t"

  "$mod ALT, o, exec, audio-switcher output"
  "$mod ALT, i, exec, audio-switcher input"
  "$mod ALT, p, exec, pavucontrol"
  "$mod ALT, q, exec, qpwgraph"
  "$mod ALT, h, exec, helvum"
  "$mod ALT, e, exec, easyeffects"
]
