{
  preservation.preserveAt."/persist".users.max = {
    directories = [
      {
        directory = ".ssh";
        mode = "0700";
      }
      {
        directory = ".gnupg";
        mode = "0700";
      }
      {
        directory = ".local/share/keyrings";
        mode = "0700";
      }

      # Browser logins
      ".config/net.imput.helium"

      # Comics
      ".local/share/komikku"

      # ponytail: preserve mixed-state parents so atomic JSON/SQLite replacements
      # and database sidecars survive alongside BT_backup, categories and RSS.
      # Home Manager still replaces qBittorrent.conf and qBittorrent-data.conf;
      # GUI changes to those generated files do not survive HM activation.
      # Copy both directories to /persist/home/max before the first mount,
      # with qBittorrent stopped; Nix regenerates managed config/plugin links.
      ".config/qBittorrent"
      ".local/share/qBittorrent"

      # Graphics editors (user prefs, palettes, recent files, plugins)
      ".config/aseprite"
      ".config/Blockbench"
      ".config/GIMP"

      # Office suite preferences, templates, dictionaries, and extensions
      ".config/libreoffice"

      # OBS Studio scenes, profiles, settings, and user-installed plugins
      ".config/obs-studio"

      # Gaming
      ".config/r2modmanPlus-local"
      ".local/share/Steam"
      ".local/share/PrismLauncher"
      ".local/share/Paradox Interactive"
      ".local/share/Tabletop Simulator"
      ".local/share/SlayTheSpire2"

      # Switch emulator (firmware, prod.keys, saves, mods)
      ".config/Ryujinx"

      # Chat
      ".config/Signal"
      ".config/vesktop"
      ".config/TeamSpeak"
      ".cache/TeamSpeak"

      # User data
      "Documents"
      "Downloads"
      "Pictures"
      "Videos"
      "Music"
      "workspace"

      # Desktop state
      ".config/dconf"

      # IntelliJ settings and user-installed plugins
      ".config/JetBrains"
      ".local/share/JetBrains"

      # Gradle wrapper distributions and dependency cache
      ".gradle"

      # JetBrains Java prefs registry: stores the accepted EULA/ToS
      # version (and license tokens). Without this the ToS prompt
      # reappears on every tmpfs-root boot. (.java/fonts is a
      # regenerable cache and is intentionally not persisted.)
      ".java/.userPrefs"

      # Noctalia GUI/runtime state. The declarative config remains
      # generated by home-manager; this only preserves app-managed
      # acknowledgements and UI state so first-run prompts do not
      # reappear on every tmpfs-root boot.
      ".local/state/noctalia"

      # Shell history
      ".local/share/fish"

      # Direnv approvals for reviewed .envrc content
      ".local/share/direnv"

      # Zoxide directory database
      ".local/share/zoxide"

      # Serialized Zellij sessions for resurrection after reboot
      ".cache/zellij"

      # WirePlumber sound device settings
      ".local/state/wireplumber"

      # TIDAL Chrome app login session and preferences
      ".config/tidal"

      # Solaar — Logitech device settings (scroll wheel resolution,
      # SmartShift, DPI, button mappings). Without this, mouse
      # settings reset to factory defaults on every reboot.
      ".config/solaar"

      # Nix user profile GC roots
      ".local/state/nix"
      # Nix trusted flake settings, including permanently accepted
      # flake-provided binary caches.
      ".local/share/nix"

      # Amp CLI session + credentials
      ".amp"
      ".config/amp"
      ".local/share/amp"

      # Claude Code settings + credentials (manually configured for GLM Coding Plan)
      ".claude"

      # Codex CLI auth + history + config
      ".codex"

      # OMP coding agent auth, config, and sessions
      ".omp"

      # ML model weights and dataset caches — large downloads
      # (HuggingFace hub, torch hub, torchvision pretrained
      # checkpoints) that should survive reboots.
      ".cache/huggingface"
      ".cache/torch"

      # uv wheel cache — recreating venvs is instant when this
      # survives reboots, otherwise every venv re-downloads
      # multi-GB torch+rocm wheels.
      ".cache/uv"
      ".local/share/uv"
    ];

    files = [
      # Claude Code state file: hasCompletedOnboarding, theme, OAuth session,
      # MCP user-scope config, per-project trust. Without this, claude prompts
      # for theme/trust on every boot.
      ".claude.json"
    ];
  };
}
